name: Build Windows

env:
  project: PopEngine
  AUTH_TOKEN: ${{ secrets.PACKAGE_KEY_ACTIONS }}

on:
  push:
    branches:
      - master
      - '*Test*'

jobs:
  Build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com/
          scope: '@newchromantics'
          node-version: 12
  
      - name: Install Github Packages
        working-directory: ${{ env.project }}.Package/
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ env.AUTH_TOKEN }}

      - name: Copy package downloads to Libs
        run: |
          mkdir -p Libs
          cp ${{ env.project }}.Package/node_modules/@newchromantics/* Libs
          ls -R Libs

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1
  
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Windows
        uses: NewChromantics/PopAction_BuildWindows@v1
        with:
          BuildPlatform: x64
          BuildConfiguration: Release
          # would be nice to extract this from visual studio
          BuildDirectory: Build\Release_x6
          project: ${{ env.project }}
